//
// Created by Yossi Levi on 08/06/2019.
//

#include <iostream>
#include <string.h>
using std::string;
#include "../eurovision.h"

using std::cout;
using std::endl;



void TEST7(){
    freopen ("../test7myresult.txt","w",stdout);
    MainControl eurovision;
    Participant p1("france","song_france",201,"singer_france");
    cout<<p1<<endl;
    Participant p2("russia","song_russia",187,"singer_russia");
    cout<<p2<<endl;
    Participant p3("belgium","song_belgium",136,"singer_belgium");
    cout<<p3<<endl;
    Participant p4("italy","song_italy",134,"singer_italy");
    cout<<p4<<endl;
    Participant p5("italy","song_italy",194,"singer_italy");
    cout<<p5<<endl;
    Participant p6("georgia","song_georgia",203,"singer_georgia");
    cout<<p6<<endl;
    Participant p7("luxembourg","song_luxembourg",194,"singer_luxembourg");
    cout<<p7<<endl;
    Participant p8("latvia","song_latvia",154,"singer_latvia");
    cout<<p8<<endl;
    Participant p9("italy","song_italy",120,"singer_italy");
    cout<<p9<<endl;
    Participant p10("kazakhastan","song_kazakhastan",158,"singer_kazakhastan");
    cout<<p10<<endl;
    Participant p11("croatia","song_croatia",111,"singer_croatia");
    cout<<p11<<endl;
    Participant p12("uk","song_uk",134,"singer_uk");
    cout<<p12<<endl;
    Participant p13("malta","song_malta",227,"singer_malta");
    cout<<p13<<endl;
    Participant p14("georgia","song_georgia",192,"singer_georgia");
    cout<<p14<<endl;
    Participant p15("bulgaria","song_bulgaria",164,"singer_bulgaria");
    cout<<p15<<endl;
    Participant p16("switzerland","song_switzerland",114,"singer_switzerland");
    cout<<p16<<endl;
    Participant p17("armenia","song_armenia",107,"singer_armenia");
    cout<<p17<<endl;
    Participant p18("slovakia","song_slovakia",124,"singer_slovakia");
    cout<<p18<<endl;
    Participant p19("france","song_france",197,"singer_france");
    cout<<p19<<endl;
    Participant p20("latvia","song_latvia",211,"singer_latvia");
    cout<<p20<<endl;
    Participant p21("russia","song_russia",114,"singer_russia");
    cout<<p21<<endl;
    Participant p22("bulgaria","song_bulgaria",176,"singer_bulgaria");
    cout<<p22<<endl;
    Participant p23("greece","song_greece",167,"singer_greece");
    cout<<p23<<endl;
    Participant p24("latvia","song_latvia",146,"singer_latvia");
    cout<<p24<<endl;
    Participant p25("moldova","song_moldova",110,"singer_moldova");
    cout<<p25<<endl;
    Participant p26("belgium","song_belgium",119,"singer_belgium");
    cout<<p26<<endl;
    Participant p27("france","song_france",168,"singer_france");
    cout<<p27<<endl;
    Participant p28("belgium","song_belgium",115,"singer_belgium");
    cout<<p28<<endl;
    Participant p29("armenia","song_armenia",111,"singer_armenia");
    cout<<p29<<endl;
    Participant p30("latvia","song_latvia",200,"singer_latvia");
    cout<<p30<<endl;
    Participant p31("malta","song_malta",167,"singer_malta");
    cout<<p31<<endl;
    Participant p32("luxembourg","song_luxembourg",207,"singer_luxembourg");
    cout<<p32<<endl;
    Participant p33("latvia","song_latvia",146,"singer_latvia");
    cout<<p33<<endl;
    Participant p34("armenia","song_armenia",105,"singer_armenia");
    cout<<p34<<endl;
    Participant p35("austria","song_austria",152,"singer_austria");
    cout<<p35<<endl;
    Participant p36("estonia","song_estonia",159,"singer_estonia");
    cout<<p36<<endl;
    p32.update("new_song",0,"");
    p29.update("new_song",0,"");
    p34.update("new_song",0,"");
    p16.update("new_song",0,"");
    p7.update("new_song",0,"newsinger");
    p21.update("new_song",0,"newsinger");
    p12.update("new_song",0,"newsinger");
    p32.update("new_song",0,"newsinger");
    p2.update("new_song",146,"newsinger");
    p17.update("new_song",140,"newsinger");
    p23.update("new_song",120,"newsinger");
    p24.update("new_song",183,"newsinger");
    cout<<eurovision<<endl;
    eurovision+=p27;
    eurovision+=p9;
    eurovision+=p35;
    eurovision+=p15;
    eurovision+=p5;
    eurovision+=p7;
    eurovision+=p3;
    eurovision+=p14;
    eurovision+=p12;
    eurovision+=p11;
    eurovision+=p2;
    eurovision+=p6;
    eurovision+=p4;
    eurovision+=p16;
    cout<<eurovision<<endl;
    eurovision+=p7;
    eurovision+=p7;
    eurovision+=p27;
    eurovision+=p26;
    eurovision-=p21;
    eurovision+=p7;
    eurovision+=p3;
    eurovision-=p21;
    eurovision+=p35;
    eurovision+=p3;
    eurovision+=p15;
    eurovision+=p8;
    eurovision-=p26;
    eurovision+=p10;
    eurovision-=p27;
    eurovision+=p32;
    eurovision+=p5;
    eurovision+=p12;
    eurovision-=p34;
    eurovision+=p7;
    eurovision+=p18;
    eurovision+=p33;
    eurovision-=p11;
    eurovision+=p16;
    cout<<eurovision<<endl;
    (((eurovision-=p18)+=p1)+=p22)+=p27;
    eurovision.setPhase(Contest);
    eurovision.setPhase(Voting);
    std::cout<<eurovision.participate("malta")<<std::endl;
    std::cout<<eurovision.participate("moldova")<<std::endl;
    std::cout<<eurovision.participate("switzerland")<<std::endl;
    std::cout<<eurovision.participate("norway")<<std::endl;
    std::cout<<eurovision.participate("estonia")<<std::endl;
    std::cout<<eurovision.participate("moldova")<<std::endl;
    std::cout<<eurovision.participate("austria")<<std::endl;
    std::cout<<eurovision.participate("turkey")<<std::endl;
    std::cout<<eurovision.participate("bulgaria")<<std::endl;
    std::cout<<eurovision.participate("germany")<<std::endl;
    std::cout<<eurovision.participate("malta")<<std::endl;
    std::cout<<eurovision.participate("bulgaria")<<std::endl;
    std::cout<<eurovision.participate("moldova")<<std::endl;
    std::cout<<eurovision.participate("bulgaria")<<std::endl;
    p33.update("",120,"");
    cout<<p33<<endl;
    p11.update("",120,"");
    cout<<p11<<endl;
    p22.update("",120,"");
    cout<<p22<<endl;
    p22.update("",120,"");
    cout<<p22<<endl;
    p21.update("",120,"");
    cout<<p21<<endl;
    p10.update("",120,"");
    cout<<p10<<endl;
    p34.update("",120,"");
    cout<<p34<<endl;
    p35.update("",120,"");
    cout<<p35<<endl;
    p11.update("",120,"");
    cout<<p11<<endl;
    p14.update("",120,"");
    cout<<p14<<endl;
    p11.update("",120,"");
    cout<<p11<<endl;
    p23.update("",120,"");
    cout<<p23<<endl;
    p8.update("",120,"");
    cout<<p8<<endl;
    p30.update("",120,"");
    cout<<p30<<endl;
    Voter v1("ireland",Regular);
    Voter v2("bosnia",Judge);
    Voter v3("ireland");
    Voter v4("lithiania");
    Voter v5("kazakhastan",Regular);
    Voter v6("israel",Regular);
    Voter v7("kazakhastan");
    Voter v8("uk",Regular);
    Voter v9("norway",Judge);
    Voter v10("germany",Regular);
    Voter v11("belgium",Judge);
    Voter v12("kazakhastan",Regular);
    Voter v13("georgia",Judge);
    Voter v14("italy",Regular);
    Voter v15("armenia",Regular);
    Voter v16("sweden",Regular);
    Voter v17("germany",Regular);
    Voter v18("georgia");
    Voter v19("turkey");
    Voter v20("switzerland",Judge);
    Voter v21("serbia",Judge);
    Voter v22("armenia");
    Voter v23("switzerland",Regular);
    Voter v24("luxembourg",Regular);
    Voter v25("germany",Judge);
    Voter v26("ireland",Regular);
    Voter v27("moldova",Regular);
    Voter v28("estonia");
    Voter v29("moldova");
    Voter v30("spain",Judge);
    Voter v31("serbia");
    Voter v32("uk",Judge);
    Voter v33("bosnia",Regular);
    Voter v34("kazakhastan");
    Voter v35("spain");
    Voter v36("uk");
    Voter v37("belgium",Judge);
    Voter v38("andora",Judge);
    Voter v39("cyrpus",Regular);
    Voter v40("slovakia",Judge);
    Voter v41("ukraine");
    Voter v42("slovenia",Regular);
    Voter v43("belarus",Judge);
    Voter v44("spain",Judge);
    Voter v45("bosnia");
    Voter v46("bulgaria",Judge);
    Voter v47("italy");
    Voter v48("uk");
    Voter v49("netherlands");
    Voter v50("andora",Regular);
    Voter v51("france");
    Voter v52("ukraine");
    Voter v53("serbia");
    Voter v54("norway",Regular);
    Voter v55("slovakia");
    Voter v56("greece");
    Voter v57("malta",Judge);
    Voter v58("malta");
    Voter v59("croatia",Judge);
    Voter v60("slovakia",Judge);
    Voter v61("sweden",Regular);
    Voter v62("ireland");
    Voter v63("russia",Regular);
    Voter v64("sweden");
    Voter v65("bulgaria",Judge);
    Voter v66("slovenia");
    Voter v67("spain");
    Voter v68("georgia",Regular);
    Voter v69("andora",Regular);
    Voter v70("austria");
    Voter v71("turkey");
    Voter v72("slovenia",Judge);
    Voter v73("georgia",Judge);
    Voter v74("sweden");
    Voter v75("germany",Regular);
    Voter v76("belarus",Judge);
    Voter v77("ireland",Judge);
    Voter v78("spain",Regular);
    Voter v79("croatia",Regular);
    Voter v80("norway",Judge);
    Voter v81("uk",Regular);
    Voter v82("luxembourg",Judge);
    Voter v83("turkey",Judge);
    Voter v84("sweden");
    Voter v85("slovakia",Judge);
    Voter v86("kazakhastan");
    Voter v87("bosnia");
    Voter v88("lithiania");
    Voter v89("latvia",Regular);
    Voter v90("slovakia",Regular);
    Voter v91("france");
    Voter v92("russia");
    Voter v93("kazakhastan");
    Voter v94("lithiania");
    Voter v95("armenia");
    Voter v96("ukraine",Judge);
    Voter v97("sweden",Judge);
    Voter v98("armenia");
    Voter v99("sweden",Regular);
    cout<<eurovision<<endl;
    eurovision+=Vote(v83,"hungary","israel","kazakhastan","italy","greece","norway","netherlands","luxembourg");
    eurovision+=Vote(v77,"israel","sweden","russia","belarus","ireland","kazakhastan");
    eurovision+=Vote(v85,"turkey","sweden","germany","greece","latvia","armenia");
    eurovision+=Vote(v99,"armenia");
    eurovision+=Vote(v12,"israel");
    eurovision+=Vote(v38,"germany","russia");
    eurovision+=Vote(v41,"bosnia");
    eurovision+=Vote(v42,"georgia");
    eurovision+=Vote(v4,"slovenia");
    eurovision+=Vote(v25,"norway","slovenia","lithiania","sweden","latvia","germany","norway");
    eurovision+=Vote(v48,"serbia");
    eurovision+=Vote(v31,"kazakhastan");
    eurovision+=Vote(v68,"moldova");
    eurovision+=Vote(v17,"latvia");
    eurovision+=Vote(v96,"austria","georgia","italy","bulgaria","switzerland","germany","luxembourg");
    eurovision+=Vote(v31,"sweden");
    eurovision+=Vote(v52,"latvia");
    eurovision+=Vote(v47,"serbia");
    eurovision+=Vote(v34,"serbia");
    eurovision+=Vote(v83,"spain","georgia","croatia","norway","andora","latvia","kazakhastan","germany");
    eurovision+=Vote(v62,"norway");
    eurovision+=Vote(v13,"moldova","latvia","lithiania","moldova","norway","sweden","france","estonia","turkey");
    eurovision+=Vote(v32,"bulgaria","norway","germany","turkey","andora","hungary","estonia","malta","italy","slovakia");
    eurovision+=Vote(v62,"lithiania");
    eurovision+=Vote(v93,"slovakia");
    eurovision+=Vote(v22,"hungary");
    eurovision+=Vote(v76,"georgia","turkey","austria","belgium","latvia","norway","slovenia");
    eurovision+=Vote(v3,"italy");
    eurovision+=Vote(v25,"greece","austria","turkey");
    eurovision+=Vote(v44,"germany","slovakia","georgia","bulgaria","spain","france","belarus");
    eurovision+=Vote(v61,"slovakia");
    eurovision+=Vote(v27,"armenia");
    eurovision+=Vote(v26,"turkey");
    eurovision+=Vote(v56,"lithiania");
    eurovision+=Vote(v7,"greece");
    eurovision+=Vote(v90,"latvia");
    eurovision+=Vote(v10,"russia");
    eurovision+=Vote(v21,"bosnia","hungary","armenia","lithiania","moldova");
    eurovision+=Vote(v57,"ireland","switzerland","ireland","slovakia","bosnia","spain","slovenia");
    eurovision+=Vote(v6,"hungary");
    eurovision+=Vote(v4,"france");
    eurovision+=Vote(v92,"ireland");
    eurovision+=Vote(v80,"luxembourg","latvia","serbia","sweden");
    eurovision+=Vote(v15,"sweden");
    eurovision+=Vote(v61,"estonia");
    eurovision+=Vote(v94,"sweden");
    eurovision+=Vote(v85,"moldova","russia","israel","switzerland","malta","georgia","bulgaria","norway","austria","turkey");
    eurovision+=Vote(v65,"netherlands","serbia");
    eurovision+=Vote(v7,"georgia");
    eurovision+=Vote(v50,"armenia");
    eurovision+=Vote(v81,"lithiania");
    eurovision+=Vote(v3,"lithiania");
    eurovision+=Vote(v14,"serbia");
    eurovision+=Vote(v88,"sweden");
    eurovision+=Vote(v39,"israel");
    eurovision+=Vote(v39,"slovakia");
    eurovision+=Vote(v28,"slovakia");
    eurovision+=Vote(v37,"cyrpus","ukraine","germany","bulgaria","kazakhastan");
    eurovision+=Vote(v84,"moldova");
    eurovision+=Vote(v52,"hungary");
    eurovision+=Vote(v49,"andora");
    eurovision+=Vote(v77,"moldova","malta","italy","sweden","france","netherlands","switzerland");
    eurovision+=Vote(v22,"germany");
    eurovision+=Vote(v74,"bulgaria");
    eurovision+=Vote(v18,"netherlands");
    eurovision+=Vote(v94,"luxembourg");
    eurovision+=Vote(v68,"netherlands");
    eurovision+=Vote(v33,"italy");
    eurovision+=Vote(v19,"moldova");
    eurovision+=Vote(v53,"kazakhastan");
    eurovision+=Vote(v83,"norway","serbia","turkey","sweden","slovenia","belarus","croatia");
    eurovision+=Vote(v23,"slovenia");
    eurovision+=Vote(v80,"kazakhastan","netherlands","latvia","spain","bosnia");
    eurovision+=Vote(v28,"spain");
    eurovision+=Vote(v80,"germany","armenia","slovenia","cyrpus","croatia","ireland","estonia");
    eurovision+=Vote(v24,"hungary");
    eurovision+=Vote(v36,"serbia");
    eurovision+=Vote(v99,"spain");
    eurovision+=Vote(v82,"austria","latvia","norway","moldova");
    eurovision+=Vote(v87,"greece");
    eurovision+=Vote(v77,"georgia","croatia","italy","austria");
    eurovision+=Vote(v51,"slovakia");
    eurovision+=Vote(v89,"armenia");
    eurovision+=Vote(v77,"slovenia","slovakia","andora","belarus","spain");
    eurovision+=Vote(v31,"belgium");
    eurovision+=Vote(v74,"greece");
    eurovision+=Vote(v49,"norway");
    eurovision+=Vote(v35,"estonia");
    eurovision+=Vote(v20,"belarus","italy");
    eurovision+=Vote(v93,"ukraine");
    eurovision+=Vote(v77,"bosnia","greece");
    eurovision+=Vote(v64,"bosnia");
    eurovision+=Vote(v96,"kazakhastan","malta","bulgaria","serbia","latvia","italy");
    eurovision+=Vote(v81,"russia");
    eurovision+=Vote(v11,"italy","estonia","latvia","croatia","germany","serbia","kazakhastan");
    eurovision+=Vote(v16,"israel");
    eurovision+=Vote(v16,"estonia");
    eurovision+=Vote(v96,"latvia","latvia","bulgaria","estonia","greece");
    eurovision+=Vote(v32,"kazakhastan","sweden","belarus","norway","turkey","slovenia");
    eurovision+=Vote(v64,"kazakhastan");
    eurovision+=Vote(v85,"cyrpus","spain","germany","luxembourg","armenia","netherlands","andora","belarus","austria");
    eurovision+=Vote(v6,"luxembourg");
    eurovision+=Vote(v63,"croatia");
    eurovision+=Vote(v89,"israel");
    eurovision+=Vote(v90,"armenia");
    eurovision+=Vote(v92,"greece");
    eurovision+=Vote(v72,"sweden","norway","russia","greece","malta","bulgaria","belgium");
    eurovision+=Vote(v87,"serbia");
    eurovision+=Vote(v4,"switzerland");
    eurovision+=Vote(v30,"estonia","israel");
    eurovision+=Vote(v9,"armenia","switzerland","france","bosnia","norway","greece","lithiania","andora","armenia");
    eurovision+=Vote(v50,"ukraine");
    eurovision+=Vote(v39,"ireland");
    eurovision+=Vote(v58,"croatia");
    eurovision+=Vote(v30,"slovenia","estonia","switzerland","turkey","slovenia","andora","israel","sweden");
    eurovision+=Vote(v63,"slovenia");
    eurovision+=Vote(v27,"italy");
    eurovision+=Vote(v19,"estonia");
    eurovision+=Vote(v76,"russia","bulgaria","switzerland","belarus","ireland","italy","armenia","netherlands");
    eurovision+=Vote(v98,"kazakhastan");
    eurovision+=Vote(v93,"armenia");
    eurovision+=Vote(v20,"andora","ukraine","serbia","norway","austria");
    eurovision+=Vote(v77,"italy","georgia","serbia");
    eurovision+=Vote(v68,"croatia");
    eurovision+=Vote(v57,"belgium","italy","bosnia","estonia","slovakia","serbia");
    eurovision+=Vote(v56,"slovakia");
    eurovision+=Vote(v22,"norway");
    eurovision+=Vote(v2,"turkey","latvia","belgium","russia","greece");
    eurovision+=Vote(v26,"lithiania");
    eurovision+=Vote(v61,"estonia");
    eurovision+=Vote(v36,"belgium");
    eurovision+=Vote(v47,"netherlands");
    eurovision+=Vote(v1,"slovenia");
    eurovision+=Vote(v83,"ukraine","lithiania","slovakia","croatia","ukraine","bulgaria","switzerland","armenia");
    eurovision+=Vote(v5,"spain");
    eurovision+=Vote(v34,"france");
    eurovision+=Vote(v93,"latvia");
    eurovision+=Vote(v85,"spain","france","ireland","ukraine","malta","greece","bulgaria");
    eurovision+=Vote(v13,"hungary","georgia","croatia","cyrpus","belgium","hungary","lithiania","armenia","malta");
    eurovision+=Vote(v53,"estonia");
    eurovision+=Vote(v45,"switzerland");
    eurovision+=Vote(v16,"georgia");
    eurovision+=Vote(v43,"greece","serbia","ukraine");
    eurovision+=Vote(v45,"andora");
    eurovision+=Vote(v93,"latvia");
    eurovision+=Vote(v48,"germany");
    eurovision+=Vote(v74,"armenia");
    eurovision+=Vote(v2,"georgia","bulgaria","croatia");
    eurovision+=Vote(v18,"armenia");
    eurovision+=Vote(v83,"france","croatia","ireland","georgia","moldova");
    eurovision+=Vote(v90,"kazakhastan");
    eurovision+=Vote(v5,"turkey");
    eurovision+=Vote(v5,"kazakhastan");
    eurovision+=Vote(v14,"france");
    eurovision+=Vote(v32,"netherlands","russia","cyrpus","sweden","belgium","bulgaria","norway");
    eurovision+=Vote(v41,"turkey");
    eurovision+=Vote(v6,"ireland");
    eurovision+=Vote(v17,"malta");
    eurovision+=Vote(v2,"croatia","croatia");
    eurovision+=Vote(v96,"slovakia","estonia","moldova","switzerland","norway","slovenia","armenia");
    eurovision+=Vote(v32,"belgium","bosnia","netherlands","lithiania","georgia","slovakia");
    eurovision+=Vote(v89,"lithiania");
    eurovision+=Vote(v93,"andora");
    eurovision+=Vote(v1,"ireland");
    eurovision+=Vote(v24,"slovakia");
    eurovision+=Vote(v9,"sweden","russia","hungary","luxembourg","latvia");
    eurovision+=Vote(v67,"slovenia");
    eurovision+=Vote(v70,"slovenia");
    eurovision+=Vote(v10,"slovakia");
    eurovision+=Vote(v1,"germany");
    eurovision+=Vote(v54,"norway");
    eurovision+=Vote(v1,"hungary");
    eurovision+=Vote(v1,"luxembourg");
    eurovision+=Vote(v26,"greece");
    eurovision+=Vote(v88,"ukraine");
    eurovision+=Vote(v16,"greece");
    eurovision+=Vote(v72,"georgia","israel");
    eurovision+=Vote(v36,"kazakhastan");
    eurovision+=Vote(v41,"armenia");
    eurovision+=Vote(v54,"sweden");
    eurovision+=Vote(v45,"lithiania");
    eurovision+=Vote(v49,"ireland");
    eurovision+=Vote(v52,"italy");
    eurovision+=Vote(v70,"italy");
    eurovision+=Vote(v75,"france");
    eurovision+=Vote(v41,"luxembourg");
    eurovision+=Vote(v87,"bosnia");
    eurovision+=Vote(v75,"spain");
    eurovision+=Vote(v18,"luxembourg");
    eurovision+=Vote(v80,"greece","bulgaria","andora","serbia","austria","norway","belgium","sweden");
    eurovision+=Vote(v80,"armenia","austria");
    eurovision+=Vote(v50,"belgium");
    eurovision+=Vote(v67,"ukraine");
    eurovision+=Vote(v34,"austria");
    eurovision+=Vote(v30,"serbia","armenia");
    eurovision+=Vote(v96,"serbia","russia","greece","israel","armenia","turkey");
    eurovision+=Vote(v15,"ireland");
    eurovision+=Vote(v8,"serbia");
    eurovision+=Vote(v56,"germany");
    cout<<eurovision<<endl;

}
