//
// Created by Yossi Levi on 08/06/2019.
//

#include <iostream>
#include <string.h>
using std::string;
#include "../eurovision.h"

using std::cout;
using std::endl;



void TEST2 (){
    freopen ("../test2myresult.txt","w",stdout);
    MainControl eurovision;
    Participant p1("croatia","song_croatia",112,"singer_croatia");
    cout<<p1<<endl;
    Participant p2("georgia","song_georgia",195,"singer_georgia");
    cout<<p2<<endl;
    Participant p3("norway","song_norway",112,"singer_norway");
    cout<<p3<<endl;
    Participant p4("germany","song_germany",131,"singer_germany");
    cout<<p4<<endl;
    Participant p5("austria","song_austria",228,"singer_austria");
    cout<<p5<<endl;
    Participant p6("luxembourg","song_luxembourg",220,"singer_luxembourg");
    cout<<p6<<endl;
    Participant p7("slovakia","song_slovakia",227,"singer_slovakia");
    cout<<p7<<endl;
    Participant p8("estonia","song_estonia",133,"singer_estonia");
    cout<<p8<<endl;
    Participant p9("france","song_france",169,"singer_france");
    cout<<p9<<endl;
    Participant p10("bulgaria","song_bulgaria",176,"singer_bulgaria");
    cout<<p10<<endl;
    Participant p11("slovakia","song_slovakia",113,"singer_slovakia");
    cout<<p11<<endl;
    Participant p12("lithiania","song_lithiania",100,"singer_lithiania");
    cout<<p12<<endl;
    Participant p13("ukraine","song_ukraine",184,"singer_ukraine");
    cout<<p13<<endl;
    Participant p14("russia","song_russia",172,"singer_russia");
    cout<<p14<<endl;
    Participant p15("bulgaria","song_bulgaria",183,"singer_bulgaria");
    cout<<p15<<endl;
    Participant p16("uk","song_uk",148,"singer_uk");
    cout<<p16<<endl;
    Participant p17("belarus","song_belarus",200,"singer_belarus");
    cout<<p17<<endl;
    Participant p18("uk","song_uk",112,"singer_uk");
    cout<<p18<<endl;
    Participant p19("belgium","song_belgium",109,"singer_belgium");
    cout<<p19<<endl;
    Participant p20("lithiania","song_lithiania",210,"singer_lithiania");
    cout<<p20<<endl;
    Participant p21("israel","song_israel",213,"singer_israel");
    cout<<p21<<endl;
    Participant p22("israel","song_israel",153,"singer_israel");
    cout<<p22<<endl;
    Participant p23("russia","song_russia",223,"singer_russia");
    cout<<p23<<endl;
    Participant p24("croatia","song_croatia",178,"singer_croatia");
    cout<<p24<<endl;
    Participant p25("bulgaria","song_bulgaria",222,"singer_bulgaria");
    cout<<p25<<endl;
    Participant p26("netherlands","song_netherlands",216,"singer_netherlands");
    cout<<p26<<endl;
    Participant p27("andora","song_andora",211,"singer_andora");
    cout<<p27<<endl;
    Participant p28("georgia","song_georgia",115,"singer_georgia");
    cout<<p28<<endl;
    Participant p29("slovakia","song_slovakia",207,"singer_slovakia");
    cout<<p29<<endl;
    Participant p30("belgium","song_belgium",128,"singer_belgium");
    cout<<p30<<endl;
    Participant p31("bulgaria","song_bulgaria",213,"singer_bulgaria");
    cout<<p31<<endl;
    Participant p32("malta","song_malta",156,"singer_malta");
    cout<<p32<<endl;
    Participant p33("uk","song_uk",190,"singer_uk");
    cout<<p33<<endl;
    Participant p34("hungary","song_hungary",157,"singer_hungary");
    cout<<p34<<endl;
    Participant p35("luxembourg","song_luxembourg",206,"singer_luxembourg");
    cout<<p35<<endl;
    Participant p36("ireland","song_ireland",183,"singer_ireland");
    cout<<p36<<endl;
    p28.update("new_song",0,"");
    p17.update("new_song",0,"");
    p27.update("new_song",0,"");
    p8.update("new_song",0,"");
    p25.update("new_song",0,"newsinger");
    p8.update("new_song",0,"newsinger");
    p24.update("new_song",0,"newsinger");
    p3.update("new_song",0,"newsinger");
    p10.update("new_song",139,"newsinger");
    p32.update("new_song",121,"newsinger");
    p4.update("new_song",125,"newsinger");
    p15.update("new_song",151,"newsinger");
    cout<<eurovision<<endl;
    eurovision+=p7;
    eurovision+=p15;
    eurovision+=p19;
    eurovision+=p14;
    eurovision+=p15;
    eurovision+=p7;
    eurovision+=p15;
    eurovision+=p28;
    eurovision+=p35;
    eurovision+=p35;
    eurovision+=p10;
    eurovision+=p35;
    eurovision+=p28;
    eurovision+=p22;
    cout<<eurovision<<endl;
    eurovision-=p5;
    eurovision+=p18;
    eurovision-=p29;
    eurovision+=p33;
    eurovision-=p17;
    eurovision-=p14;
    eurovision+=p5;
    eurovision+=p22;
    eurovision-=p13;
    eurovision+=p29;
    eurovision+=p13;
    eurovision+=p14;
    eurovision-=p15;
    eurovision+=p30;
    eurovision+=p19;
    eurovision+=p32;
    eurovision+=p33;
    eurovision-=p35;
    eurovision+=p2;
    eurovision+=p15;
    eurovision-=p22;
    eurovision+=p2;
    eurovision-=p3;
    eurovision-=p35;
    cout<<eurovision<<endl;
    (((((((((((((eurovision+=p24)-=p13)-=p32)+=p13)+=p1)-=p25)+=p26)+=p16)+=p31)
    -=p1)+=p12)+=p8)+=p5)+=p11;
    eurovision.setPhase(Contest);
    eurovision.setPhase(Voting);
    std::cout<<eurovision.participate("bosnia")<<std::endl;
    std::cout<<eurovision.participate("luxembourg")<<std::endl;
    std::cout<<eurovision.participate("turkey")<<std::endl;
    std::cout<<eurovision.participate("serbia")<<std::endl;
    std::cout<<eurovision.participate("belgium")<<std::endl;
    std::cout<<eurovision.participate("croatia")<<std::endl;
    std::cout<<eurovision.participate("germany")<<std::endl;
    std::cout<<eurovision.participate("luxembourg")<<std::endl;
    std::cout<<eurovision.participate("slovakia")<<std::endl;
    std::cout<<eurovision.participate("lithiania")<<std::endl;
    std::cout<<eurovision.participate("austria")<<std::endl;
    std::cout<<eurovision.participate("hungary")<<std::endl;
    std::cout<<eurovision.participate("belarus")<<std::endl;
    std::cout<<eurovision.participate("slovakia")<<std::endl;
    p12.update("",120,"");
    cout<<p12<<endl;
    p14.update("",120,"");
    cout<<p14<<endl;
    p31.update("",120,"");
    cout<<p31<<endl;
    p31.update("",120,"");
    cout<<p31<<endl;
    p35.update("",120,"");
    cout<<p35<<endl;
    p34.update("",120,"");
    cout<<p34<<endl;
    p1.update("",120,"");
    cout<<p1<<endl;
    p24.update("",120,"");
    cout<<p24<<endl;
    p31.update("",120,"");
    cout<<p31<<endl;
    p4.update("",120,"");
    cout<<p4<<endl;
    p23.update("",120,"");
    cout<<p23<<endl;
    p23.update("",120,"");
    cout<<p23<<endl;
    p11.update("",120,"");
    cout<<p11<<endl;
    p8.update("",120,"");
    cout<<p8<<endl;
    Voter v1("lithiania",Judge);
    Voter v2("kazakhastan");
    Voter v3("netherlands",Regular);
    Voter v4("norway",Regular);
    Voter v5("malta");
    Voter v6("israel",Judge);
    Voter v7("croatia");
    Voter v8("luxembourg",Judge);
    Voter v9("ireland",Judge);
    Voter v10("latvia");
    Voter v11("luxembourg");
    Voter v12("latvia");
    Voter v13("cyrpus");
    Voter v14("malta");
    Voter v15("germany",Judge);
    Voter v16("malta",Judge);
    Voter v17("ukraine",Judge);
    Voter v18("georgia",Judge);
    Voter v19("malta",Judge);
    Voter v20("kazakhastan");
    Voter v21("sweden");
    Voter v22("ireland",Judge);
    Voter v23("sweden");
    Voter v24("andora",Regular);
    Voter v25("croatia",Judge);
    Voter v26("estonia",Regular);
    Voter v27("andora",Judge);
    Voter v28("russia",Regular);
    Voter v29("georgia",Regular);
    Voter v30("estonia",Judge);
    Voter v31("italy",Regular);
    Voter v32("uk",Regular);
    Voter v33("bosnia",Judge);
    Voter v34("belgium");
    Voter v35("greece",Regular);
    Voter v36("turkey",Judge);
    Voter v37("france");
    Voter v38("georgia");
    Voter v39("greece");
    Voter v40("belgium",Judge);
    Voter v41("france",Judge);
    Voter v42("serbia");
    Voter v43("spain",Regular);
    Voter v44("switzerland",Judge);
    Voter v45("lithiania",Regular);
    Voter v46("greece");
    Voter v47("israel");
    Voter v48("hungary",Judge);
    Voter v49("slovakia",Regular);
    Voter v50("moldova");
    Voter v51("croatia");
    Voter v52("austria",Regular);
    Voter v53("spain",Regular);
    Voter v54("spain",Judge);
    Voter v55("russia",Regular);
    Voter v56("ukraine");
    Voter v57("ireland",Regular);
    Voter v58("israel");
    Voter v59("hungary",Judge);
    Voter v60("kazakhastan",Regular);
    Voter v61("russia",Judge);
    Voter v62("france");
    Voter v63("switzerland");
    Voter v64("austria",Regular);
    Voter v65("estonia",Regular);
    Voter v66("russia");
    Voter v67("austria");
    Voter v68("andora",Regular);
    Voter v69("serbia",Judge);
    Voter v70("russia");
    Voter v71("estonia",Regular);
    Voter v72("luxembourg");
    Voter v73("italy");
    Voter v74("spain");
    Voter v75("spain",Judge);
    Voter v76("germany",Regular);
    Voter v77("hungary",Regular);
    Voter v78("estonia");
    Voter v79("croatia",Judge);
    Voter v80("luxembourg",Judge);
    Voter v81("georgia");
    Voter v82("switzerland",Judge);
    Voter v83("hungary");
    Voter v84("latvia",Regular);
    Voter v85("norway",Regular);
    Voter v86("belgium");
    Voter v87("greece");
    Voter v88("germany",Judge);
    Voter v89("sweden",Judge);
    Voter v90("belarus",Judge);
    Voter v91("cyrpus",Judge);
    Voter v92("armenia");
    Voter v93("croatia");
    Voter v94("georgia");
    Voter v95("armenia",Regular);
    Voter v96("spain",Judge);
    Voter v97("malta");
    Voter v98("andora");
    Voter v99("sweden");
    cout<<eurovision<<endl;
    eurovision+=Vote(v25,"ukraine","serbia","greece","germany","austria","netherlands","croatia","turkey","bosnia");
    eurovision+=Vote(v20,"france");
    eurovision+=Vote(v26,"cyrpus");
    eurovision+=Vote(v45,"bosnia");
    eurovision+=Vote(v52,"ireland");
    eurovision+=Vote(v59,"malta","netherlands","slovakia","estonia","austria","greece");
    eurovision+=Vote(v97,"andora");
    eurovision+=Vote(v26,"italy");
    eurovision+=Vote(v79,"croatia","latvia","cyrpus","georgia","bulgaria","ireland","luxembourg","bosnia");
    eurovision+=Vote(v71,"malta");
    eurovision+=Vote(v35,"kazakhastan");
    eurovision+=Vote(v79,"germany","turkey","france","croatia","netherlands","spain","bosnia","kazakhastan","andora");
    eurovision+=Vote(v43,"malta");
    eurovision+=Vote(v35,"luxembourg");
    eurovision+=Vote(v56,"lithiania");
    eurovision+=Vote(v8,"bulgaria","belgium","ukraine","lithiania");
    eurovision+=Vote(v68,"austria");
    eurovision+=Vote(v5,"moldova");
    eurovision+=Vote(v43,"belgium");
    eurovision+=Vote(v18,"ukraine","italy","luxembourg","moldova","israel","hungary");
    eurovision+=Vote(v95,"ireland");
    eurovision+=Vote(v95,"russia");
    eurovision+=Vote(v15,"ireland","armenia","slovenia","cyrpus","serbia","georgia","kazakhastan","slovakia","france");
    eurovision+=Vote(v36,"spain","norway","kazakhastan","lithiania","belgium","georgia","sweden","spain");
    eurovision+=Vote(v67,"armenia");
    eurovision+=Vote(v42,"ukraine");
    eurovision+=Vote(v81,"latvia");
    eurovision+=Vote(v38,"lithiania");
    eurovision+=Vote(v37,"germany");
    eurovision+=Vote(v63,"spain");
    eurovision+=Vote(v3,"italy");
    eurovision+=Vote(v96,"norway","bosnia","norway","kazakhastan","estonia","slovakia","georgia","israel");
    eurovision+=Vote(v12,"malta");
    eurovision+=Vote(v33,"cyrpus","luxembourg","norway","georgia","israel","austria","ukraine");
    eurovision+=Vote(v90,"latvia","austria","france","croatia","georgia","ukraine","spain");
    eurovision+=Vote(v54,"austria","georgia","belgium","serbia","italy","bosnia","russia","lithiania","france");
    eurovision+=Vote(v18,"greece","switzerland","lithiania");
    eurovision+=Vote(v52,"sweden");
    eurovision+=Vote(v71,"germany");
    eurovision+=Vote(v35,"georgia");
    eurovision+=Vote(v5,"slovenia");
    eurovision+=Vote(v46,"kazakhastan");
    eurovision+=Vote(v35,"latvia");
    eurovision+=Vote(v92,"turkey");
    eurovision+=Vote(v84,"hungary");
    eurovision+=Vote(v61,"norway","cyrpus","estonia");
    eurovision+=Vote(v65,"spain");
    eurovision+=Vote(v7,"luxembourg");
    eurovision+=Vote(v92,"ireland");
    eurovision+=Vote(v26,"kazakhastan");
    eurovision+=Vote(v13,"bosnia");
    eurovision+=Vote(v52,"luxembourg");
    eurovision+=Vote(v42,"serbia");
    eurovision+=Vote(v8,"greece","bosnia","norway");
    eurovision+=Vote(v91,"estonia","bosnia","luxembourg");
    eurovision+=Vote(v57,"bulgaria");
    eurovision+=Vote(v51,"slovakia");
    eurovision+=Vote(v1,"lithiania","estonia");
    eurovision+=Vote(v52,"russia");
    eurovision+=Vote(v80,"israel","serbia","hungary","sweden","latvia","netherlands","turkey","moldova");
    eurovision+=Vote(v74,"belarus");
    eurovision+=Vote(v77,"israel");
    eurovision+=Vote(v31,"russia");
    eurovision+=Vote(v38,"italy");
    eurovision+=Vote(v80,"belgium","malta","slovenia","armenia");
    eurovision+=Vote(v33,"slovakia","slovenia","slovakia","israel","ukraine","georgia","andora","bosnia","estonia");
    eurovision+=Vote(v52,"turkey");
    eurovision+=Vote(v58,"austria");
    eurovision+=Vote(v81,"andora");
    eurovision+=Vote(v3,"belarus");
    eurovision+=Vote(v33,"bulgaria","turkey","spain","serbia","bulgaria");
    eurovision+=Vote(v81,"estonia");
    eurovision+=Vote(v27,"slovenia","bulgaria","georgia","israel");
    eurovision+=Vote(v75,"cyrpus","netherlands","switzerland","hungary","italy","turkey","armenia");
    eurovision+=Vote(v4,"belarus");
    eurovision+=Vote(v36,"switzerland","cyrpus","slovenia","sweden","lithiania");
    eurovision+=Vote(v14,"austria");
    eurovision+=Vote(v36,"armenia","turkey","hungary","armenia","slovakia","austria","belarus");
    eurovision+=Vote(v72,"malta");
    eurovision+=Vote(v98,"andora");
    eurovision+=Vote(v64,"serbia");
    eurovision+=Vote(v30,"latvia","greece","turkey","hungary");
    eurovision+=Vote(v62,"malta");
    eurovision+=Vote(v49,"moldova");
    eurovision+=Vote(v98,"switzerland");
    eurovision+=Vote(v64,"cyrpus");
    eurovision+=Vote(v72,"lithiania");
    eurovision+=Vote(v23,"luxembourg");
    eurovision+=Vote(v58,"croatia");
    eurovision+=Vote(v63,"malta");
    eurovision+=Vote(v57,"slovenia");
    eurovision+=Vote(v6,"croatia","france","georgia","slovenia","latvia","sweden","slovakia","luxembourg");
    eurovision+=Vote(v93,"andora");
    eurovision+=Vote(v32,"belgium");
    eurovision+=Vote(v35,"luxembourg");
    eurovision+=Vote(v63,"latvia");
    eurovision+=Vote(v98,"ukraine");
    eurovision+=Vote(v49,"norway");
    eurovision+=Vote(v3,"andora");
    eurovision+=Vote(v10,"italy");
    eurovision+=Vote(v32,"turkey");
    eurovision+=Vote(v88,"hungary","israel","kazakhastan","switzerland","slovenia","luxembourg","belgium");
    eurovision+=Vote(v46,"france");
    eurovision+=Vote(v78,"austria");
    eurovision+=Vote(v28,"spain");
    eurovision+=Vote(v38,"italy");
    eurovision+=Vote(v35,"kazakhastan");
    eurovision+=Vote(v65,"slovenia");
    eurovision+=Vote(v59,"moldova","slovenia");
    eurovision+=Vote(v13,"lithiania");
    eurovision+=Vote(v92,"armenia");
    eurovision+=Vote(v26,"latvia");
    eurovision+=Vote(v44,"greece","slovakia","belgium","armenia","switzerland");
    eurovision+=Vote(v62,"moldova");
    eurovision+=Vote(v25,"serbia","ireland","israel","georgia");
    eurovision+=Vote(v72,"sweden");
    eurovision+=Vote(v97,"kazakhastan");
    eurovision+=Vote(v65,"luxembourg");
    eurovision+=Vote(v81,"latvia");
    eurovision+=Vote(v48,"slovakia","belarus","bosnia","switzerland","croatia","moldova");
    eurovision+=Vote(v32,"ireland");
    eurovision+=Vote(v91,"andora","greece","bulgaria","austria","moldova","norway","georgia","andora");
    eurovision+=Vote(v85,"slovenia");
    eurovision+=Vote(v4,"austria");
    eurovision+=Vote(v1,"norway","georgia","cyrpus","russia","luxembourg","croatia");
    eurovision+=Vote(v70,"georgia");
    eurovision+=Vote(v29,"austria");
    eurovision+=Vote(v7,"luxembourg");
    eurovision+=Vote(v50,"switzerland");
    eurovision+=Vote(v24,"slovakia");
    eurovision+=Vote(v9,"italy","serbia");
    eurovision+=Vote(v64,"slovakia");
    eurovision+=Vote(v94,"germany");
    eurovision+=Vote(v77,"luxembourg");
    eurovision+=Vote(v67,"austria");
    eurovision+=Vote(v33,"norway","armenia","netherlands","israel","lithiania","ukraine","bulgaria","hungary","cyrpus");
    eurovision+=Vote(v88,"slovenia","netherlands","bosnia","austria","lithiania");
    eurovision+=Vote(v25,"germany","estonia","ukraine","latvia","bosnia");
    eurovision+=Vote(v34,"serbia");
    eurovision+=Vote(v39,"estonia");
    eurovision+=Vote(v46,"latvia");
    eurovision+=Vote(v18,"sweden","moldova","austria","spain");
    eurovision+=Vote(v7,"armenia");
    eurovision+=Vote(v45,"serbia");
    eurovision+=Vote(v84,"malta");
    eurovision+=Vote(v67,"germany");
    eurovision+=Vote(v1,"norway","france","ukraine","turkey");
    eurovision+=Vote(v82,"norway","moldova","belarus");
    eurovision+=Vote(v56,"ireland");
    eurovision+=Vote(v61,"moldova","malta","slovenia","lithiania");
    eurovision+=Vote(v74,"kazakhastan");
    eurovision+=Vote(v90,"moldova","turkey","norway","slovenia","spain","bulgaria","germany","andora","armenia");
    eurovision+=Vote(v75,"bosnia","malta","greece","bosnia","hungary","turkey","luxembourg","spain","cyrpus");
    eurovision+=Vote(v93,"moldova");
    eurovision+=Vote(v87,"slovenia");
    eurovision+=Vote(v85,"turkey");
    eurovision+=Vote(v53,"israel");
    eurovision+=Vote(v73,"israel");
    eurovision+=Vote(v78,"lithiania");
    eurovision+=Vote(v54,"italy","israel");
    eurovision+=Vote(v18,"andora","slovenia","armenia","france","switzerland","ireland","belarus","slovakia","belgium");
    eurovision+=Vote(v57,"ireland");
    eurovision+=Vote(v55,"moldova");
    eurovision+=Vote(v35,"croatia");
    eurovision+=Vote(v55,"georgia");
    eurovision+=Vote(v2,"ireland");
    eurovision+=Vote(v55,"bosnia");
    eurovision+=Vote(v19,"turkey","croatia","israel","norway","turkey","belarus","cyrpus");
    eurovision+=Vote(v72,"france");
    eurovision+=Vote(v41,"latvia","lithiania","luxembourg","andora","estonia","slovenia","moldova","latvia");
    eurovision+=Vote(v38,"greece");
    eurovision+=Vote(v81,"belgium");
    eurovision+=Vote(v10,"croatia");
    eurovision+=Vote(v22,"ireland","norway","cyrpus");
    eurovision+=Vote(v26,"sweden");
    eurovision+=Vote(v3,"israel");
    eurovision+=Vote(v31,"slovenia");
    eurovision+=Vote(v2,"norway");
    eurovision+=Vote(v22,"austria","netherlands","cyrpus");
    eurovision+=Vote(v15,"andora","israel","switzerland","norway","hungary","sweden");
    eurovision+=Vote(v18,"russia","lithiania","armenia","croatia","ireland","russia");
    eurovision+=Vote(v57,"slovakia");
    eurovision+=Vote(v50,"cyrpus");
    eurovision+=Vote(v78,"slovenia");
    eurovision+=Vote(v22,"lithiania","belgium","germany");
    eurovision+=Vote(v12,"moldova");
    eurovision+=Vote(v72,"croatia");
    eurovision+=Vote(v29,"estonia");
    eurovision+=Vote(v60,"bosnia");
    eurovision+=Vote(v39,"luxembourg");
    eurovision+=Vote(v26,"italy");
    eurovision+=Vote(v95,"greece");
    eurovision+=Vote(v59,"russia","russia","greece","slovakia","norway","croatia","estonia","switzerland","bulgaria");
    eurovision+=Vote(v83,"spain");
    eurovision+=Vote(v57,"latvia");
    eurovision+=Vote(v26,"armenia");
    eurovision+=Vote(v88,"germany","cyrpus");
    eurovision+=Vote(v22,"luxembourg","sweden");
    eurovision+=Vote(v96,"latvia","cyrpus","armenia","turkey","luxembourg","kazakhastan","bosnia");
    cout<<eurovision<<endl;

}
