//
// Created by Yossi Levi on 08/06/2019.
//

#include <iostream>
#include <string.h>
using std::string;
#include "../eurovision.h"

using std::cout;
using std::endl;
#include <fstream>


void TEST10(){
    freopen ("../test10myresult.txt","w",stdout);
    MainControl eurovision;
    Participant p1("georgia","song_georgia",194,"singer_georgia");
    cout<<p1<<endl;
    Participant p2("belarus","song_belarus",201,"singer_belarus");
    cout<<p2<<endl;
    Participant p3("croatia","song_croatia",210,"singer_croatia");
    cout<<p3<<endl;
    Participant p4("belarus","song_belarus",219,"singer_belarus");
    cout<<p4<<endl;
    Participant p5("bulgaria","song_bulgaria",106,"singer_bulgaria");
    cout<<p5<<endl;
    Participant p6("latvia","song_latvia",135,"singer_latvia");
    cout<<p6<<endl;
    Participant p7("ukraine","song_ukraine",107,"singer_ukraine");
    cout<<p7<<endl;
    Participant p8("greece","song_greece",129,"singer_greece");
    cout<<p8<<endl;
    Participant p9("slovenia","song_slovenia",187,"singer_slovenia");
    cout<<p9<<endl;
    Participant p10("croatia","song_croatia",191,"singer_croatia");
    cout<<p10<<endl;
    Participant p11("russia","song_russia",217,"singer_russia");
    cout<<p11<<endl;
    Participant p12("estonia","song_estonia",190,"singer_estonia");
    cout<<p12<<endl;
    Participant p13("israel","song_israel",114,"singer_israel");
    cout<<p13<<endl;
    Participant p14("bosnia","song_bosnia",225,"singer_bosnia");
    cout<<p14<<endl;
    Participant p15("luxembourg","song_luxembourg",203,"singer_luxembourg");
    cout<<p15<<endl;
    Participant p16("malta","song_malta",156,"singer_malta");
    cout<<p16<<endl;
    Participant p17("croatia","song_croatia",106,"singer_croatia");
    cout<<p17<<endl;
    Participant p18("croatia","song_croatia",186,"singer_croatia");
    cout<<p18<<endl;
    Participant p19("ukraine","song_ukraine",119,"singer_ukraine");
    cout<<p19<<endl;
    Participant p20("bosnia","song_bosnia",204,"singer_bosnia");
    cout<<p20<<endl;
    Participant p21("switzerland","song_switzerland",201,"singer_switzerland");
    cout<<p21<<endl;
    Participant p22("turkey","song_turkey",212,"singer_turkey");
    cout<<p22<<endl;
    Participant p23("switzerland","song_switzerland",173,"singer_switzerland");
    cout<<p23<<endl;
    Participant p24("serbia","song_serbia",156,"singer_serbia");
    cout<<p24<<endl;
    Participant p25("austria","song_austria",115,"singer_austria");
    cout<<p25<<endl;
    Participant p26("estonia","song_estonia",223,"singer_estonia");
    cout<<p26<<endl;
    Participant p27("lithiania","song_lithiania",158,"singer_lithiania");
    cout<<p27<<endl;
    Participant p28("switzerland","song_switzerland",148,"singer_switzerland");
    cout<<p28<<endl;
    Participant p29("andora","song_andora",214,"singer_andora");
    cout<<p29<<endl;
    Participant p30("serbia","song_serbia",206,"singer_serbia");
    cout<<p30<<endl;
    Participant p31("israel","song_israel",146,"singer_israel");
    cout<<p31<<endl;
    Participant p32("malta","song_malta",208,"singer_malta");
    cout<<p32<<endl;
    Participant p33("armenia","song_armenia",206,"singer_armenia");
    cout<<p33<<endl;
    Participant p34("austria","song_austria",140,"singer_austria");
    cout<<p34<<endl;
    Participant p35("hungary","song_hungary",193,"singer_hungary");
    cout<<p35<<endl;
    Participant p36("ukraine","song_ukraine",184,"singer_ukraine");
    cout<<p36<<endl;
    p11.update("new_song",0,"");
    p21.update("new_song",0,"");
    p34.update("new_song",0,"");
    p14.update("new_song",0,"");
    p28.update("new_song",0,"newsinger");
    p8.update("new_song",0,"newsinger");
    p19.update("new_song",0,"newsinger");
    p13.update("new_song",0,"newsinger");
    p32.update("new_song",193,"newsinger");
    p31.update("new_song",148,"newsinger");
    p24.update("new_song",115,"newsinger");
    p1.update("new_song",189,"newsinger");
    cout<<eurovision<<endl;
    eurovision+=p28;
    eurovision+=p31;
    eurovision+=p16;
    eurovision+=p19;
    eurovision+=p13;
    eurovision+=p16;
    eurovision+=p17;
    eurovision+=p11;
    eurovision+=p9;
    eurovision+=p17;
    eurovision+=p9;
    eurovision+=p34;
    eurovision+=p30;
    eurovision+=p33;
    cout<<eurovision<<endl;
    eurovision+=p30;
    eurovision+=p6;
    eurovision+=p30;
    eurovision-=p36;
    eurovision+=p4;
    eurovision+=p25;
    eurovision+=p36;
    eurovision+=p14;
    eurovision+=p35;
    eurovision-=p22;
    eurovision-=p31;
    eurovision+=p20;
    eurovision+=p18;
    eurovision-=p34;
    eurovision+=p4;
    eurovision-=p11;
    eurovision+=p10;
    eurovision-=p19;
    eurovision-=p27;
    eurovision+=p9;
    eurovision-=p4;
    eurovision+=p8;
    eurovision-=p26;
    eurovision-=p2;
    cout<<eurovision<<endl;
    (((((((eurovision+=p34)-=p3)-=p2)-=p12)-=p17)+=p19)+=p7)+=p33;
    eurovision.setPhase(Contest);
    eurovision.setPhase(Voting);
    std::cout<<eurovision.participate("hungary")<<std::endl;
    std::cout<<eurovision.participate("armenia")<<std::endl;
    std::cout<<eurovision.participate("sweden")<<std::endl;
    std::cout<<eurovision.participate("serbia")<<std::endl;
    std::cout<<eurovision.participate("turkey")<<std::endl;
    std::cout<<eurovision.participate("andora")<<std::endl;
    std::cout<<eurovision.participate("moldova")<<std::endl;
    std::cout<<eurovision.participate("bosnia")<<std::endl;
    std::cout<<eurovision.participate("norway")<<std::endl;
    std::cout<<eurovision.participate("luxembourg")<<std::endl;
    std::cout<<eurovision.participate("ireland")<<std::endl;
    std::cout<<eurovision.participate("greece")<<std::endl;
    std::cout<<eurovision.participate("israel")<<std::endl;
    std::cout<<eurovision.participate("hungary")<<std::endl;
    p27.update("",120,"");
    cout<<p27<<endl;
    p25.update("",120,"");
    cout<<p25<<endl;
    p21.update("",120,"");
    cout<<p21<<endl;
    p28.update("",120,"");
    cout<<p28<<endl;
    p31.update("",120,"");
    cout<<p31<<endl;
    p14.update("",120,"");
    cout<<p14<<endl;
    p32.update("",120,"");
    cout<<p32<<endl;
    p22.update("",120,"");
    cout<<p22<<endl;
    p29.update("",120,"");
    cout<<p29<<endl;
    p15.update("",120,"");
    cout<<p15<<endl;
    p13.update("",120,"");
    cout<<p13<<endl;
    p4.update("",120,"");
    cout<<p4<<endl;
    p3.update("",120,"");
    cout<<p3<<endl;
    p6.update("",120,"");
    cout<<p6<<endl;
    Voter v1("russia",Judge);
    Voter v2("estonia",Regular);
    Voter v3("switzerland",Judge);
    Voter v4("armenia",Judge);
    Voter v5("bulgaria",Judge);
    Voter v6("moldova");
    Voter v7("croatia");
    Voter v8("moldova",Regular);
    Voter v9("ukraine");
    Voter v10("sweden");
    Voter v11("france",Regular);
    Voter v12("ukraine",Judge);
    Voter v13("turkey");
    Voter v14("luxembourg",Regular);
    Voter v15("uk",Regular);
    Voter v16("israel",Judge);
    Voter v17("france",Regular);
    Voter v18("russia",Regular);
    Voter v19("bulgaria",Regular);
    Voter v20("germany",Regular);
    Voter v21("armenia",Regular);
    Voter v22("georgia",Regular);
    Voter v23("hungary",Regular);
    Voter v24("armenia",Judge);
    Voter v25("norway");
    Voter v26("georgia",Regular);
    Voter v27("turkey",Regular);
    Voter v28("latvia",Regular);
    Voter v29("austria");
    Voter v30("ukraine");
    Voter v31("estonia");
    Voter v32("sweden",Judge);
    Voter v33("luxembourg");
    Voter v34("andora");
    Voter v35("cyrpus",Regular);
    Voter v36("slovakia",Judge);
    Voter v37("france");
    Voter v38("belarus",Judge);
    Voter v39("greece");
    Voter v40("france");
    Voter v41("spain",Regular);
    Voter v42("kazakhastan",Judge);
    Voter v43("andora",Regular);
    Voter v44("israel",Regular);
    Voter v45("ukraine",Judge);
    Voter v46("spain",Regular);
    Voter v47("slovenia",Regular);
    Voter v48("luxembourg",Regular);
    Voter v49("ireland");
    Voter v50("croatia",Judge);
    Voter v51("moldova",Judge);
    Voter v52("andora",Judge);
    Voter v53("russia",Judge);
    Voter v54("russia",Judge);
    Voter v55("belgium",Judge);
    Voter v56("malta",Regular);
    Voter v57("turkey",Regular);
    Voter v58("germany",Regular);
    Voter v59("sweden",Regular);
    Voter v60("turkey",Regular);
    Voter v61("russia");
    Voter v62("germany",Judge);
    Voter v63("latvia");
    Voter v64("moldova");
    Voter v65("armenia",Judge);
    Voter v66("israel",Judge);
    Voter v67("russia");
    Voter v68("georgia",Regular);
    Voter v69("switzerland",Regular);
    Voter v70("latvia");
    Voter v71("luxembourg",Regular);
    Voter v72("turkey",Judge);
    Voter v73("israel");
    Voter v74("georgia",Regular);
    Voter v75("kazakhastan");
    Voter v76("netherlands");
    Voter v77("netherlands");
    Voter v78("switzerland",Judge);
    Voter v79("latvia",Judge);
    Voter v80("hungary",Regular);
    Voter v81("israel",Judge);
    Voter v82("croatia");
    Voter v83("malta",Judge);
    Voter v84("turkey",Judge);
    Voter v85("georgia",Regular);
    Voter v86("ukraine");
    Voter v87("luxembourg");
    Voter v88("slovakia");
    Voter v89("estonia",Regular);
    Voter v90("slovakia",Judge);
    Voter v91("cyrpus",Regular);
    Voter v92("russia",Judge);
    Voter v93("serbia",Judge);
    Voter v94("latvia",Regular);
    Voter v95("andora",Regular);
    Voter v96("spain");
    Voter v97("hungary",Judge);
    Voter v98("netherlands",Regular);
    Voter v99("belarus",Regular);
    cout<<eurovision<<endl;
    eurovision+=Vote(v54,"spain","hungary","germany","switzerland");
    eurovision+=Vote(v96,"malta");
    eurovision+=Vote(v73,"georgia");
    eurovision+=Vote(v28,"switzerland");
    eurovision+=Vote(v99,"croatia");
    eurovision+=Vote(v20,"sweden");
    eurovision+=Vote(v38,"bulgaria","lithiania","croatia","malta");
    eurovision+=Vote(v46,"bosnia");
    eurovision+=Vote(v2,"georgia");
    eurovision+=Vote(v24,"netherlands","malta","turkey","lithiania","croatia","slovakia","belgium");
    eurovision+=Vote(v99,"bulgaria");
    eurovision+=Vote(v48,"netherlands");
    eurovision+=Vote(v1,"belarus","luxembourg","norway","germany");
    eurovision+=Vote(v5,"germany","slovenia","cyrpus","russia","israel","armenia");
    eurovision+=Vote(v5,"italy","ireland","latvia","cyrpus","hungary","armenia","greece","estonia");
    eurovision+=Vote(v94,"belgium");
    eurovision+=Vote(v42,"lithiania","france","austria","slovenia");
    eurovision+=Vote(v54,"bulgaria","sweden");
    eurovision+=Vote(v13,"belgium");
    eurovision+=Vote(v3,"kazakhastan","ireland","cyrpus","bulgaria","kazakhastan","germany","estonia","austria","armenia","sweden");
    eurovision+=Vote(v71,"israel");
    eurovision+=Vote(v68,"belgium");
    eurovision+=Vote(v4,"estonia","kazakhastan","croatia","norway","luxembourg","israel","cyrpus","moldova");
    eurovision+=Vote(v73,"malta");
    eurovision+=Vote(v39,"latvia");
    eurovision+=Vote(v90,"latvia","bosnia","turkey","serbia","bulgaria","slovakia","russia","israel");
    eurovision+=Vote(v15,"belgium");
    eurovision+=Vote(v3,"netherlands","armenia","moldova","germany","belgium","slovakia","bosnia");
    eurovision+=Vote(v79,"austria","kazakhastan","estonia","norway","luxembourg","serbia","moldova","sweden","andora");
    eurovision+=Vote(v28,"bulgaria");
    eurovision+=Vote(v61,"ukraine");
    eurovision+=Vote(v66,"croatia","switzerland");
    eurovision+=Vote(v62,"italy","spain","turkey","russia","netherlands","armenia","bosnia");
    eurovision+=Vote(v72,"norway","sweden","netherlands","latvia","bulgaria","germany","kazakhastan","slovakia","croatia");
    eurovision+=Vote(v6,"israel");
    eurovision+=Vote(v27,"hungary");
    eurovision+=Vote(v40,"armenia");
    eurovision+=Vote(v3,"hungary","armenia","russia");
    eurovision+=Vote(v19,"belarus");
    eurovision+=Vote(v30,"belarus");
    eurovision+=Vote(v23,"malta");
    eurovision+=Vote(v10,"bosnia");
    eurovision+=Vote(v31,"greece");
    eurovision+=Vote(v97,"estonia","andora","france","sweden","turkey");
    eurovision+=Vote(v6,"italy");
    eurovision+=Vote(v66,"russia","armenia","latvia","croatia","netherlands");
    eurovision+=Vote(v96,"kazakhastan");
    eurovision+=Vote(v73,"ukraine");
    eurovision+=Vote(v87,"norway");
    eurovision+=Vote(v51,"lithiania","hungary","switzerland","ireland");
    eurovision+=Vote(v73,"netherlands");
    eurovision+=Vote(v48,"serbia");
    eurovision+=Vote(v12,"france","kazakhastan","greece","andora","sweden","estonia","georgia","bosnia");
    eurovision+=Vote(v77,"bosnia");
    eurovision+=Vote(v48,"belgium");
    eurovision+=Vote(v27,"norway");
    eurovision+=Vote(v15,"netherlands");
    eurovision+=Vote(v32,"israel","croatia","ireland","ukraine","turkey","estonia","sweden","israel");
    eurovision+=Vote(v71,"israel");
    eurovision+=Vote(v94,"ireland");
    eurovision+=Vote(v82,"kazakhastan");
    eurovision+=Vote(v96,"austria");
    eurovision+=Vote(v60,"luxembourg");
    eurovision+=Vote(v52,"andora","spain","sweden","croatia","armenia","luxembourg","kazakhastan");
    eurovision+=Vote(v93,"serbia","slovenia","bosnia","ukraine","germany");
    eurovision+=Vote(v54,"israel","kazakhastan","hungary","armenia","belgium");
    eurovision+=Vote(v13,"croatia");
    eurovision+=Vote(v50,"bosnia","luxembourg","ukraine");
    eurovision+=Vote(v25,"georgia");
    eurovision+=Vote(v81,"kazakhastan","malta");
    eurovision+=Vote(v44,"hungary");
    eurovision+=Vote(v43,"hungary");
    eurovision+=Vote(v47,"ireland");
    eurovision+=Vote(v15,"latvia");
    eurovision+=Vote(v75,"switzerland");
    eurovision+=Vote(v47,"bulgaria");
    eurovision+=Vote(v45,"belgium","hungary","croatia","italy","bosnia","germany","turkey","greece");
    eurovision+=Vote(v3,"israel","sweden","netherlands","ukraine","slovakia","germany");
    eurovision+=Vote(v56,"switzerland");
    eurovision+=Vote(v99,"greece");
    eurovision+=Vote(v41,"andora");
    eurovision+=Vote(v43,"cyrpus");
    eurovision+=Vote(v17,"slovakia");
    eurovision+=Vote(v89,"france");
    eurovision+=Vote(v26,"serbia");
    eurovision+=Vote(v36,"germany","bulgaria","belarus","switzerland","germany","luxembourg","armenia","cyrpus");
    eurovision+=Vote(v98,"ireland");
    eurovision+=Vote(v6,"russia");
    eurovision+=Vote(v84,"belgium","sweden","russia","italy","moldova");
    eurovision+=Vote(v64,"france");
    eurovision+=Vote(v76,"cyrpus");
    eurovision+=Vote(v93,"ireland","austria","kazakhastan","belgium","croatia","belarus");
    eurovision+=Vote(v73,"norway");
    eurovision+=Vote(v98,"netherlands");
    eurovision+=Vote(v16,"malta","switzerland","hungary","belarus","netherlands");
    eurovision+=Vote(v85,"andora");
    eurovision+=Vote(v9,"armenia");
    eurovision+=Vote(v88,"belarus");
    eurovision+=Vote(v41,"russia");
    eurovision+=Vote(v23,"slovenia");
    eurovision+=Vote(v23,"greece");
    eurovision+=Vote(v81,"ukraine","netherlands","lithiania");
    eurovision+=Vote(v89,"italy");
    eurovision+=Vote(v49,"ukraine");
    eurovision+=Vote(v50,"serbia","ireland","germany","sweden","bulgaria","ukraine","serbia","belgium","hungary","estonia");
    eurovision+=Vote(v3,"turkey","austria","france","kazakhastan","estonia","italy","turkey","hungary","ukraine");
    eurovision+=Vote(v49,"ireland");
    eurovision+=Vote(v43,"israel");
    eurovision+=Vote(v93,"belgium","israel","estonia","cyrpus","sweden","turkey");
    eurovision+=Vote(v70,"lithiania");
    eurovision+=Vote(v87,"greece");
    eurovision+=Vote(v28,"belarus");
    eurovision+=Vote(v46,"georgia");
    eurovision+=Vote(v86,"hungary");
    eurovision+=Vote(v51,"luxembourg","germany","sweden","spain","switzerland","cyrpus");
    eurovision+=Vote(v63,"estonia");
    eurovision+=Vote(v42,"ukraine","netherlands","armenia","ireland","slovenia");
    eurovision+=Vote(v91,"estonia");
    eurovision+=Vote(v47,"israel");
    eurovision+=Vote(v61,"sweden");
    eurovision+=Vote(v62,"russia","croatia","latvia","belgium");
    eurovision+=Vote(v47,"ireland");
    eurovision+=Vote(v37,"switzerland");
    eurovision+=Vote(v2,"andora");
    eurovision+=Vote(v3,"armenia","austria");
    eurovision+=Vote(v79,"estonia","bulgaria","spain","norway");
    eurovision+=Vote(v99,"ukraine");
    eurovision+=Vote(v67,"italy");
    eurovision+=Vote(v28,"belgium");
    eurovision+=Vote(v90,"slovenia","serbia","russia","norway","lithiania","croatia","israel","bulgaria");
    eurovision+=Vote(v59,"austria");
    eurovision+=Vote(v67,"armenia");
    eurovision+=Vote(v36,"malta","israel","luxembourg","croatia","russia");
    eurovision+=Vote(v99,"bosnia");
    eurovision+=Vote(v22,"andora");
    eurovision+=Vote(v9,"ireland");
    eurovision+=Vote(v14,"georgia");
    eurovision+=Vote(v27,"serbia");
    eurovision+=Vote(v83,"russia","serbia","france","greece","switzerland");
    eurovision+=Vote(v79,"italy","latvia");
    eurovision+=Vote(v37,"belarus");
    eurovision+=Vote(v83,"georgia","serbia","spain","belgium");
    eurovision+=Vote(v32,"estonia","austria","france","georgia","slovenia","germany");
    eurovision+=Vote(v14,"malta");
    eurovision+=Vote(v58,"lithiania");
    eurovision+=Vote(v76,"armenia");
    eurovision+=Vote(v71,"switzerland");
    eurovision+=Vote(v93,"estonia","belarus","russia","switzerland");
    eurovision+=Vote(v11,"andora");
    eurovision+=Vote(v23,"lithiania");
    eurovision+=Vote(v21,"hungary");
    eurovision+=Vote(v21,"estonia");
    eurovision+=Vote(v42,"andora","armenia");
    eurovision+=Vote(v37,"ireland");
    eurovision+=Vote(v47,"moldova");
    eurovision+=Vote(v8,"sweden");
    eurovision+=Vote(v84,"norway","italy","kazakhastan","estonia","switzerland","croatia","hungary");
    eurovision+=Vote(v25,"andora");
    eurovision+=Vote(v22,"slovakia");
    eurovision+=Vote(v91,"italy");
    eurovision+=Vote(v12,"moldova","armenia","malta","andora","serbia","russia","belgium","bulgaria");
    eurovision+=Vote(v85,"kazakhastan");
    eurovision+=Vote(v91,"norway");
    eurovision+=Vote(v9,"luxembourg");
    eurovision+=Vote(v31,"andora");
    eurovision+=Vote(v32,"belarus","andora","greece","switzerland","slovenia");
    eurovision+=Vote(v91,"bulgaria");
    eurovision+=Vote(v12,"ireland","hungary","switzerland","moldova","italy");
    eurovision+=Vote(v67,"slovenia");
    eurovision+=Vote(v16,"moldova","israel","malta","lithiania");
    eurovision+=Vote(v63,"ireland");
    eurovision+=Vote(v78,"lithiania","austria");
    eurovision+=Vote(v60,"switzerland");
    eurovision+=Vote(v84,"malta","spain","russia","estonia","germany","lithiania","bulgaria","ukraine");
    eurovision+=Vote(v11,"luxembourg");
    eurovision+=Vote(v29,"norway");
    eurovision+=Vote(v44,"luxembourg");
    eurovision+=Vote(v41,"norway");
    eurovision+=Vote(v57,"andora");
    eurovision+=Vote(v95,"germany");
    eurovision+=Vote(v44,"israel");
    eurovision+=Vote(v61,"cyrpus");
    eurovision+=Vote(v43,"serbia");
    eurovision+=Vote(v8,"italy");
    eurovision+=Vote(v94,"russia");
    eurovision+=Vote(v94,"serbia");
    eurovision+=Vote(v51,"moldova","sweden","greece");
    eurovision+=Vote(v82,"israel");
    eurovision+=Vote(v77,"italy");
    eurovision+=Vote(v54,"greece","croatia","israel","luxembourg","russia","lithiania","estonia");
    eurovision+=Vote(v76,"italy");
    eurovision+=Vote(v97,"luxembourg","switzerland","cyrpus","bosnia","greece","netherlands","malta");
    eurovision+=Vote(v48,"croatia");
    eurovision+=Vote(v60,"sweden");
    eurovision+=Vote(v39,"andora");
    eurovision+=Vote(v61,"armenia");
    eurovision+=Vote(v30,"turkey");
    eurovision+=Vote(v63,"slovenia");
    eurovision+=Vote(v92,"cyrpus","switzerland");
    cout<<eurovision<<endl;
    fclose (stdout);

}
